spring:
  thymeleaf:
    cache: false
  datasource:
    dbcp2:
      test-while-idle: true
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/iotplextest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        read-only: false
        username: root
        password: 12345678
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/iotplextest2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        read-only: true
        username: root
        password: 12345678
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 80
logging:
  file:
    name:
