spring:
  thymeleaf:
    cache: false
  datasource:
    dbcp2:
      test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iotplextest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345678
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 80
logging:
  file:
    name:
